<script lang="ts">
  import { onMount, untrack } from 'svelte';
  import { UserPlus, Copy, Database, HardDrive, Check, RefreshCw, ShieldCheck } from '@lucide/svelte';
  import { api, errorMessage } from '../lib/api';
  import { bytes, initials, type User, type StorageStatus } from '../lib/types';
  let { users, storage, onchanged }: { users: User[]; storage: StorageStatus | null; onchanged: () => void } = $props();
  let email = $state(''); let link = $state(''); let busy = $state(false); let error = $state(''); let success = $state(''); let limitMiB = $state<number | undefined>(untrack(() => (storage?.limit_bytes || 0) / 1048576));
  let deliveries = $state<{ id: number; state: string; attempts: number; error: string; message: string; recipient: string }[]>([]);
  onMount(() => { void api<typeof deliveries>('/admin/deliveries').then(v => deliveries = v).catch(e => error = errorMessage(e)); });
  async function run(work: () => Promise<void>, message = '') { busy = true; error = ''; success = ''; try { await work(); success = message; onchanged(); } catch (e) { error = errorMessage(e); } finally { busy = false; } }
  function issue(address: string, purpose: string) { void run(async () => { const result = await api<{ url: string }>('/admin/tokens', 'POST', { email: address, purpose }); link = result.url; }, purpose === 'invite' ? 'Invitation created. Share the link with your teammate.' : 'Reset link created. Share it after verifying the employee.'); }
  function changeUser(user: User, role: string, active: boolean) { if (!active && !confirm(`Deactivate ${user.name}? Their sessions and Discord access will be revoked. Their assigned work remains visible.`)) return; void run(async () => { await api(`/admin/users/${user.id}`, 'PATCH', { role, active }); }, 'Account updated.'); }
  function setLimit(event: SubmitEvent) { event.preventDefault(); const limit = Math.round((limitMiB || 0) * 1048576); if (limit > 0 && limit < (storage?.database_bytes || 0) && !confirm('This is below the current database size. New content will be blocked immediately. Continue?')) return; void run(async () => { await api('/admin/settings', 'PATCH', { max_db_bytes: limit }); }, 'Database threshold saved.'); }
</script>
<div class="settings-layout admin-layout">
  {#if error}<div class="notice danger" role="alert">{error}</div>{/if}{#if success}<div class="notice success" role="status"><Check size={16}/>{success}</div>{/if}
  <section class="settings-card"><div class="settings-card-heading"><h2><UserPlus size={19}/>Bring your team together</h2><p>Everyone in the workspace can access every project.</p></div><form class="invite-form" onsubmit={(e) => { e.preventDefault(); issue(email, 'invite'); }}><input type="email" aria-label="Invite email" bind:value={email} placeholder="teammate@company.com" required/><button class="button primary" disabled={busy}>Create invitation</button></form>
    {#if link}<div class="copy-field"><input readonly value={link} aria-label="Invitation or reset link" onclick={(e) => e.currentTarget.select()}/><button class="icon-button" title="Copy link" aria-label="Copy invitation or reset link" onclick={() => run(() => navigator.clipboard.writeText(link), 'Link copied.')}><Copy size={16}/></button></div><p class="field-hint">Invitations expire after 7 days. Password reset links expire after 30 minutes. Share links through your existing company channels.</p>{/if}
    <div class="people-list">{#each users as person}<div class="person-row" class:inactive={!person.active}><span class="avatar">{initials(person.name)}</span><div class="person-info"><strong>{person.name}</strong><small>{person.email}{person.active ? '' : ' · Deactivated'}</small></div><select aria-label={`Role for ${person.name}`} value={person.role} disabled={busy || !person.active} onchange={(e) => changeUser(person, e.currentTarget.value, person.active)}><option value="viewer">Viewer</option><option value="editor">Editor</option></select>{#if person.active}<button class="text-button" disabled={busy} onclick={() => issue(person.email, 'reset')}>Reset password</button>{/if}<button class="text-button" disabled={busy} onclick={() => changeUser(person, person.role, !person.active)}>{person.active ? 'Deactivate' : 'Reactivate'}</button></div>{/each}</div>
  </section>
  <section class="settings-card"><div class="settings-card-heading"><h2><Database size={19}/>Storage, under your control</h2><p>Text, images, and application records share one SQLite database.</p></div>{#if storage}<div class="storage-cards"><div><small>Database size</small><strong>{bytes(storage.database_bytes)}</strong><span>{storage.database_bytes.toLocaleString()} bytes</span></div><div><small>Included image content</small><strong>{bytes(storage.image_bytes)}</strong><span>{bytes(storage.max_image_bytes)} maximum per image</span></div><div><small>Write-ahead log</small><strong>{bytes(storage.wal_bytes)}</strong><span>Additional disk space; outside the threshold</span></div></div>
      <form class="threshold-form" onsubmit={setLimit}><label>Content threshold (MiB)<input type="number" min="0" step="0.01" bind:value={limitMiB} required/></label><button class="button secondary" disabled={busy}>Save threshold</button></form><p class="field-hint">0 means unlimited. The threshold uses SQLite's allocated page size, including images. Uploads that would exceed it are rolled back. Viewing, signing in, completion, and deletion remain available. Operational records and the WAL may still grow.</p>
      {#if storage.content_blocked}<div class="notice danger"><HardDrive size={18}/>New content is blocked. Purge archived tasks, remove images, or raise the threshold.</div>{/if}
    {/if}</section>
  <section class="settings-card"><div class="settings-card-heading"><h2><ShieldCheck size={19}/>Discord connection</h2><p>Bot credentials and the company server are configured by your container operator.</p></div><div class="integration-connected"><span class:online-dot={storage?.discord_connected} class:offline-dot={!storage?.discord_connected}></span><strong>{storage?.discord_connected ? 'Connected' : storage?.discord_configured ? 'Configured, waiting for connection' : 'Not configured'}</strong><span class="muted">/status reports the current database size.</span></div>
    <div class="section-label delivery-heading">Delivery issues<span class="count">{deliveries.length}</span>{#if deliveries.length}<button class="text-button" disabled={busy} onclick={() => run(async () => { await api('/admin/deliveries/retry', 'POST'); deliveries = await api('/admin/deliveries'); }, 'Failed deliveries queued for retry.')}><RefreshCw size={14}/>Retry failed</button>{/if}</div>
    {#each deliveries as delivery}<div class="delivery-row"><strong>{delivery.recipient}</strong><span>{delivery.message}</span><small>{delivery.error} · {delivery.attempts} attempts</small></div>{:else}<p class="field-hint">No delivery issues to report.</p>{/each}
  </section>
</div>
