<script lang="ts">
  import { onMount, untrack } from 'svelte';
  import { Sun, Moon, Monitor, Check, Link, Copy, Unplug, ShieldCheck, KeyRound } from '@lucide/svelte';
  import { api, errorMessage } from '../lib/api';
  import type { User, Session, StorageStatus } from '../lib/types';
  let { session, storage, onsaved, onpasswordchanged }: { session: Session; storage: StorageStatus | null; onsaved: () => void; onpasswordchanged: () => void } = $props();
  let form = $state<User>(untrack(() => ({ ...session.user }))); let busy = $state(false); let error = $state(''); let success = $state('');
  let currentPassword = $state(''); let password = $state(''); let code = $state(''); let discord = $state(untrack(() => session.discord)); let pending = $state(untrack(() => session.pending_discord));
  const zones = ['UTC', ...Intl.supportedValuesOf('timeZone')];
  onMount(() => { const timer = setInterval(() => { if (code) void api<Session>('/auth/me').then(s => { discord = s.discord; pending = s.pending_discord; }).catch(() => {}); }, 4000); return () => clearInterval(timer); });
  async function run(work: () => Promise<void>, message = '') { busy = true; error = ''; success = ''; try { await work(); success = message; } catch (e) { error = errorMessage(e); } finally { busy = false; } }
  function save(e: SubmitEvent) { e.preventDefault(); void run(async () => { await api('/me', 'PATCH', form); onsaved(); }, 'Preferences saved.'); }
  function changePassword(e: SubmitEvent) { e.preventDefault(); void run(async () => { await api('/me/change-password', 'POST', { current_password: currentPassword, password }); currentPassword = ''; password = ''; onpasswordchanged(); }); }
  function startLink() { void run(async () => { const result = await api<{ code: string }>('/me/discord/link-token', 'POST'); code = result.code; pending = null; }); }
  function confirmLink() { void run(async () => { await api('/me/discord/confirm', 'POST', { discord_id: pending?.id }); const updated = await api<Session>('/auth/me'); discord = updated.discord; pending = null; code = ''; onsaved(); }, 'Discord connected.'); }
  function unlink() { if (!confirm('Disconnect Discord? Taskboard notifications will still be available here.')) return; void run(async () => { await api('/me/discord', 'DELETE'); code = ''; discord = null; pending = null; onsaved(); }, 'Discord disconnected.'); }
</script>
<div class="settings-layout">
  {#if error}<div class="notice danger" role="alert">{error}</div>{/if}{#if success}<div class="notice success" role="status"><Check size={16}/>{success}</div>{/if}
  <form onsubmit={save}>
    <section class="settings-card"><div class="settings-card-heading"><h2>Your profile</h2><p>The details your teammates see.</p></div><div class="settings-fields"><label>Display name<input bind:value={form.name} required maxlength="100"/></label><label>Email<input value={form.email} disabled/></label><label>Local time zone<input bind:value={form.timezone} list="timezones" required/><datalist id="timezones">{#each zones as zone}<option value={zone}></option>{/each}</datalist></label></div><p class="field-hint">Taskboard stores timestamps in UTC and shows them in this time zone. New or changed due dates also use this time zone.</p></section>
    <section class="settings-card"><div class="settings-card-heading"><h2>Make it feel like you</h2><p>Choose how Taskboard looks on your screen.</p></div><div class="theme-options">{#each [{ value: 'light' as const, label: 'Light', icon: Sun }, { value: 'dark' as const, label: 'Dark', icon: Moon }, { value: 'system' as const, label: 'System', icon: Monitor }] as option}<label class:selected={form.theme === option.value}><input type="radio" name="theme" value={option.value} bind:group={form.theme}/><div class="theme-preview" class:dark-preview={option.value === 'dark'} class:system-preview={option.value === 'system'}><span></span><div><i></i><i></i><i></i></div></div><span><option.icon size={16}/>{option.label}{#if form.theme === option.value}<Check size={14}/>{/if}</span></label>{/each}</div></section>
    <section class="settings-card"><div class="settings-card-heading"><h2>Stay in the loop</h2><p>Decide which updates reach you, and where.</p></div><div class="preference-grid"><span></span><strong>In Taskboard</strong><strong>Discord DM</strong><span>Activity on watched tasks</span><input type="checkbox" aria-label="In-app activity notifications" bind:checked={form.activity_in_app}/><input type="checkbox" aria-label="Discord activity notifications" bind:checked={form.activity_discord}/><span>Due dates for assigned tasks</span><input type="checkbox" aria-label="In-app due reminders" bind:checked={form.due_in_app}/><input type="checkbox" aria-label="Discord due reminders" bind:checked={form.due_discord}/></div><label class="checkbox-label"><input type="checkbox" bind:checked={form.watched_due}/>Also remind me about due dates on tasks I watch</label><p class="field-hint">Due reminders arrive at 9am the day before, the day of, and once after a missed due date, in the task's time zone.</p></section>
    <div class="settings-save"><button class="button primary" disabled={busy}>Save preferences</button></div>
  </form>
  <section class="settings-card"><div class="settings-card-heading"><h2><Link size={18}/>Discord</h2><p>Manage tasks and get updates without leaving your team's server.</p></div>
    {#if !storage?.discord_configured}<div class="notice">Your operator can enable the bot with its token and server ID in the container configuration.</div>
    {:else if discord}<div class="integration-connected"><span class="integration-badge"><ShieldCheck size={22}/></span><div><strong>Connected as {discord.name}</strong><small>Use /taskboard for tasks and /status for storage.</small></div><button class="button secondary" disabled={busy} onclick={unlink}><Unplug size={15}/>Disconnect</button></div>
    {:else}<p class="muted">Connect your Discord identity to your Taskboard account.</p><button class="button secondary" onclick={startLink} disabled={busy}>Generate linking code</button>{/if}
    {#if code}<div class="link-instructions"><p>1. Run this private command in your company Discord server (expires in 10 minutes):</p><div class="copy-field"><code>/taskboard link code:{code}</code><button class="icon-button" aria-label="Copy Discord linking command" onclick={() => run(() => navigator.clipboard.writeText(`/taskboard link code:${code}`), 'Command copied.')}><Copy size={16}/></button></div><p>2. Return here and confirm your Discord identity.</p>{#if pending}<div class="notice"><span>Connect to <strong>{pending.name}</strong> ({pending.id})?</span><button class="button primary" onclick={confirmLink} disabled={busy}>Confirm identity</button></div>{:else}<p class="field-hint">Waiting for your Discord command…</p>{/if}</div>{/if}
  </section>
  <section class="settings-card"><div class="settings-card-heading"><h2><KeyRound size={18}/>Password</h2><p>Changing your password signs out all of your sessions.</p></div><form onsubmit={changePassword}><div class="settings-fields"><label>Current password<input type="password" autocomplete="current-password" bind:value={currentPassword} required/></label><label>New password<input type="password" autocomplete="new-password" bind:value={password} required minlength="15" maxlength="1024" placeholder="At least 15 characters"/></label></div><button class="button secondary" disabled={busy}>Update password</button></form></section>
</div>
