<script lang="ts">
  import { onMount } from 'svelte';
  import { LayoutDashboard, Inbox, CheckCheck, CalendarDays, Folder, Archive, Bell, Settings as SettingsIcon, ShieldCheck, Plus, Search, List, Columns3, SlidersHorizontal, ChevronRight, ChevronDown, ArrowUpRight, LogOut, Check, Circle, Menu, X, MoreHorizontal, RefreshCw, HardDrive, Sparkles } from '@lucide/svelte';
  import Auth from './components/Auth.svelte';
  import TaskModal from './components/TaskModal.svelte';
  import ProjectModal from './components/ProjectModal.svelte';
  import Settings from './components/Settings.svelte';
  import Admin from './components/Admin.svelte';
  import Markdown from './components/Markdown.svelte';
  import { api, ApiError, errorMessage, navigate as changeRoute, setCsrf } from './lib/api';
  import { statuses, statusLabel, initials, bytes, dateLabel, timestamp, type Session, type Task, type Project, type User, type StorageStatus, type NotificationPage, type Page, type Status } from './lib/types';

  let route = $state(location.pathname); let backTo = $state('/tasks'); let session = $state<Session | null>(null); let authLoading = $state(true); let connectionError = $state('');
  let projects = $state<Project[]>([]); let users = $state<User[]>([]); let storage = $state<StorageStatus | null>(null); let notices = $state<NotificationPage>({ items: [], unread: 0, page: 1, has_more: false });
  let tasks = $state<Task[]>([]); let loading = $state(true); let listError = $state(''); let hasMore = $state(false); let page = $state(1); let requestId = 0;
  let search = $state(''); let filterStatus = $state('active'); let filterAssignee = $state(''); let filterProject = $state(''); let mode = $state('list'); let mobileNav = $state(false);
  let newTask = $state(false); let projectEditor = $state<Project | 'new' | null>(null); let showArchivedProjects = $state(false); let projectOverview = $state(false); let dragging = $state<number | null>(null);
  let toast = $state<{ message: string; action?: () => void; label?: string } | null>(null); let toastTimer: ReturnType<typeof setTimeout>;
  let taskEditor = $state<{ canLeave: () => boolean }>();
  const taskId = $derived(/^\/tasks\/TB-\d+$/.test(route) ? Number(route.split('TB-')[1]) : null);
  const screen = $derived(taskId ? backTo : route);
  const projectId = $derived(/^\/projects\/\d+$/.test(screen) ? Number(screen.split('/')[2]) : null);
  const selectedProject = $derived(projects.find(p => p.id === projectId));
  const isTaskScreen = $derived(['/my-tasks','/tasks','/due-soon','/archive'].includes(screen) || projectId !== null);
  const title = $derived(projectId ? selectedProject?.name || 'Project' : ({ '/my-tasks':'My tasks','/tasks':'All tasks','/due-soon':'Due soon','/projects':'Projects','/archive':'Archive','/notifications':'Inbox','/settings':'Settings','/admin':'Workspace management' }[screen] || 'Workspace'));
  const subtitle = $derived(projectId ? 'A shared space to move this project forward.' : ({ '/my-tasks':'Your next steps, with a little room to focus.','/tasks':'The big picture. Every project, every next step.','/due-soon':'Keep an eye on what’s coming up — and what needs a nudge.','/projects':'Give your team’s work a place to come together.','/archive':'Safely set aside. Ready to restore when you need it.','/notifications':'The updates that matter to you, all together.','/settings':'A workspace that feels a little more like you.','/admin':'A few simple controls for a well-run workspace.' }[screen] || ''));
  const activeProjects = $derived(projects.filter(p => !p.archived_at));

  function navigate(path: string) {
    if (path === route || (taskEditor && !taskEditor.canLeave())) return;
    newTask = false;
    changeRoute(path);
  }
  function go(event: MouseEvent, path: string) {
    if (event.ctrlKey || event.metaKey || event.shiftKey || event.altKey || event.button !== 0) return;
    event.preventDefault();
    navigate(path);
  }

  function notify(message: string, action?: () => void, label?: string) { clearTimeout(toastTimer); toast = { message, action, label }; toastTimer = setTimeout(() => toast = null, action ? 12000 : 6000); }
  function routeChanged() { const next = location.pathname; if (next.startsWith('/tasks/TB-') && !route.startsWith('/tasks/TB-')) backTo = route.startsWith('/projects/') || isTaskScreen ? route : '/tasks'; if (!next.startsWith('/tasks/TB-') && next !== route) { search = ''; filterStatus = 'active'; filterAssignee = ''; filterProject = ''; projectOverview = false; } route = next; mobileNav = false; }
  async function loadSession() { authLoading = true; connectionError = ''; try { session = await api<Session>('/auth/me'); setCsrf(session.csrf); if (['/','/login','/register','/reset'].includes(location.pathname)) navigate('/my-tasks'); await refreshMeta(); } catch (e) { if (e instanceof ApiError && e.status === 401) session = null; else connectionError = errorMessage(e); } finally { authLoading = false; } }
  async function refreshMeta() {
    const [p,u,s,n] = await Promise.all([api<Project[]>('/projects'),api<User[]>('/users'),api<StorageStatus>('/status'),api<NotificationPage>('/notifications')]); projects = p; users = u; storage = s; notices = n;
  }
  function query(nextPage = 1) { const q = new URLSearchParams({ page: String(nextPage), limit: '100', status: screen === '/archive' && filterStatus === 'active' ? 'all' : filterStatus }); if (projectId) q.set('project', String(projectId)); else if (filterProject) q.set('project', filterProject); if (screen === '/my-tasks') q.set('assignee', String(session!.user.id)); else if (filterAssignee) q.set('assignee', filterAssignee); if (search) q.set('q', search); if (screen === '/archive') q.set('archived', 'true'); if (screen === '/due-soon') q.set('due', 'soon'); return q.toString(); }
  async function refreshTasks(quiet = false) { if (!session || !isTaskScreen) return; const current = ++requestId; if (!quiet) loading = true; listError = ''; try { const result = await api<Page<Task>>(`/tasks?${query()}`); if (current === requestId) { tasks = result.items; hasMore = result.has_more; page = 1; } } catch (e) { if (current === requestId) listError = errorMessage(e); } finally { if (current === requestId) loading = false; } }
  async function moreTasks() { try { const result = await api<Page<Task>>(`/tasks?${query(page + 1)}`); tasks = [...tasks, ...result.items]; page = result.page; hasMore = result.has_more; } catch (e) { notify(errorMessage(e)); } }
  async function changed() { await Promise.all([refreshMeta(),refreshTasks(true)]).catch(e => notify(errorMessage(e))); }
  function openNew() { if (newTask) return; if (session?.user.role !== 'editor') return; if (storage?.content_blocked) { notify('New content is paused. Ask an editor to adjust storage or remove content.'); return; } if (!activeProjects.length) projectEditor = 'new'; else { if (taskEditor && !taskEditor.canLeave()) return; if (taskId) changeRoute(backTo); newTask = true; } }
  async function changeStatus(task: Task, status: string) { try { await api(`/tasks/${task.id}`, 'PATCH', { ...task, status }); await changed(); } catch (e) { notify(errorMessage(e)); } }
  function savedTask(task: Task | null, created = false) { void changed(); if (created && task) { newTask = false; changeRoute(`/tasks/TB-${task.id}`); notify('Task created. A little progress starts here.'); } else if (task?.archived_at) { notify('Task moved to Archive.', () => { void api(`/tasks/${task.id}/restore`, 'POST', { version: task.version }).then(() => { void changed(); notify('Task restored.'); navigate(`/tasks/TB-${task.id}`); }).catch(e => notify(errorMessage(e))); }, 'Undo'); } else notify(task ? 'Task updated.' : 'Task permanently deleted.'); }
  async function projectAction(project: Project) { if (!confirm(`${project.archived_at ? 'Restore' : 'Archive'} “${project.name}”? ${project.archived_at ? 'Its tasks will be available again.' : 'Its tasks will become read-only and due reminders will pause.'}`)) return; try { await api(`/projects/${project.id}/${project.archived_at ? 'restore' : 'archive'}`, 'POST', { version: project.version }); await changed(); notify(project.archived_at ? 'Project restored.' : 'Project archived.'); } catch (e) { notify(errorMessage(e)); } }
  async function logout() { if (taskEditor && !taskEditor.canLeave()) return; try { await api('/auth/logout','POST'); session = null; setCsrf(''); changeRoute('/login'); } catch (e) { notify(errorMessage(e)); } }
  async function markRead(id?: number) { try { await api('/notifications/read','POST',{ id: id ?? null }); notices = await api('/notifications'); } catch (e) { notify(errorMessage(e)); } }

  onMount(() => {
    void loadSession(); window.addEventListener('popstate',routeChanged); window.addEventListener('taskboard:navigate',routeChanged);
    const expired = () => { session = null; setCsrf(''); notify('Your session expired. Please sign in again.'); }; window.addEventListener('taskboard:session-expired',expired);
    const keyboard = (e: KeyboardEvent) => { if (e.key.toLowerCase() === 'c' && !e.ctrlKey && !e.metaKey && !e.altKey && session && !(e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement || e.target instanceof HTMLSelectElement) && !document.querySelector('dialog[open]')) { e.preventDefault(); openNew(); } }; window.addEventListener('keydown',keyboard);
    const timer = setInterval(() => { if (session && !document.hidden) { void refreshMeta().catch(() => {}); if (!taskId && !newTask) void refreshTasks(true); } },30000);
    return () => { clearInterval(timer); clearTimeout(toastTimer); window.removeEventListener('popstate',routeChanged); window.removeEventListener('taskboard:navigate',routeChanged); window.removeEventListener('taskboard:session-expired',expired); window.removeEventListener('keydown',keyboard); };
  });
  $effect(() => { const user = session?.user.id; const current = screen; const q = search; const status = filterStatus; const person = filterAssignee; const project = filterProject; void current; void q; void status; void person; void project; if (user) { const timer = setTimeout(() => void refreshTasks(),180); return () => clearTimeout(timer); } });
  $effect(() => { const theme = session?.user.theme; if (!theme) return; localStorage.setItem('taskboard-theme',theme); const media = matchMedia('(prefers-color-scheme: dark)'); const apply = () => document.documentElement.dataset.theme = theme === 'system' ? media.matches ? 'dark' : 'light' : theme; apply(); media.addEventListener('change',apply); return () => media.removeEventListener('change',apply); });
  $effect(() => { document.title = session ? `${title} · Taskboard` : 'Taskboard'; });
</script>

{#if authLoading}<div class="app-loading"><span class="brand-icon"><LayoutDashboard size={22}/></span><strong>taskboard.</strong><span class="spinner"></span></div>
{:else if connectionError}<div class="app-loading"><h2>Let's try that again.</h2><p>{connectionError}</p><button class="button primary" onclick={loadSession}>Reconnect</button></div>
{:else if !session}{#key route}<Auth {route} onsignedin={() => void loadSession()}/>{/key}
{:else}
  <div class="app-shell" class:task-panel-open={newTask || taskId !== null}>
    {#if mobileNav}<button class="sidebar-backdrop" aria-label="Close navigation" onclick={() => mobileNav = false}></button>{/if}
    <aside class:mobile-open={mobileNav} class="sidebar">
      <a class="brand" href="/my-tasks" onclick={(e) => go(e,'/my-tasks')}><span class="brand-icon"><LayoutDashboard size={19}/></span>taskboard<span class="brand-dot">.</span></a>
      <div class="workspace-switch"><span class="workspace-avatar">W</span><span>Your workspace<small>Shared with your team</small></span><ChevronDown size={14}/></div>
      <button class="new-task-sidebar" onclick={openNew}><Plus size={17}/>Create task<kbd>C</kbd></button>
      <nav aria-label="Workspace navigation">
        <a class:active={screen === '/my-tasks'} href="/my-tasks" onclick={(e) => go(e,'/my-tasks')}><CheckCheck size={18}/>My tasks</a>
        <a class:active={screen === '/notifications'} href="/notifications" onclick={(e) => go(e,'/notifications')}><Inbox size={18}/>Inbox{#if notices.unread}<span class="nav-count">{notices.unread}</span>{/if}</a>
        <div class="nav-section-label">WORKSPACE</div>
        <a class:active={screen === '/tasks'} href="/tasks" onclick={(e) => go(e,'/tasks')}><List size={18}/>All tasks</a>
        <a class:active={screen === '/due-soon'} href="/due-soon" onclick={(e) => go(e,'/due-soon')}><CalendarDays size={18}/>Due soon</a>
        <a class:active={screen === '/projects'} href="/projects" onclick={(e) => go(e,'/projects')}><Folder size={18}/>Projects<span class="nav-count neutral">{activeProjects.length}</span></a>
        <a class:active={screen === '/archive'} href="/archive" onclick={(e) => go(e,'/archive')}><Archive size={18}/>Archive</a>
        <div class="nav-section-label">YOUR PROJECTS{#if session.user.role === 'editor'}<button class="icon-button" aria-label="Create project" onclick={() => projectEditor = 'new'}><Plus size={14}/></button>{/if}</div>
        {#each activeProjects as project}<a class:active={projectId === project.id} href={`/projects/${project.id}`} onclick={(e) => go(e,`/projects/${project.id}`)}><span class="project-dot" style:--project-color={project.color}></span><span class="truncate">{project.name}</span></a>{:else}<p class="sidebar-empty">Good work starts with<br/>your first project.</p>{/each}
      </nav>
      <div class="sidebar-bottom">
        {#if storage}<a class="storage-mini" href={session.user.role === 'editor' ? '/admin' : '/settings'} onclick={(e) => go(e,session!.user.role === 'editor' ? '/admin' : '/settings')}><div><HardDrive size={13}/><span>{bytes(storage.database_bytes)} used</span>{#if storage.limit_bytes}<small>/ {bytes(storage.limit_bytes)}</small>{/if}</div>{#if storage.limit_bytes}<div class="storage-track"><span class:full={storage.content_blocked} style:width={`${Math.min(storage.database_bytes / storage.limit_bytes * 100,100)}%`}></span></div>{/if}</a>{/if}
        {#if session.user.role === 'editor'}<a class="bottom-nav-link" class:active={screen === '/admin'} href="/admin" onclick={(e) => go(e,'/admin')}><ShieldCheck size={16}/>Workspace management</a>{/if}
        <div class="user-section"><a href="/settings" onclick={(e) => go(e,'/settings')}><span class="avatar purple">{initials(session.user.name)}</span><span>{session.user.name}<small>{session.user.role === 'editor' ? 'Editor' : 'Viewer'}</small></span></a><button class="icon-button" aria-label="Sign out" title="Sign out" onclick={logout}><LogOut size={16}/></button></div>
      </div>
    </aside>
    <div class="main-shell">
      <header class="topbar"><div class="breadcrumbs"><button class="icon-button mobile-menu" aria-label="Open navigation" onclick={() => mobileNav = true}><Menu size={20}/></button><span class="breadcrumb-icon"><LayoutDashboard size={15}/></span><span>Workspace</span><ChevronRight size={13}/><strong>{title}</strong></div><div class="topbar-actions">{#if isTaskScreen}<div class="search-input"><Search size={16}/><input bind:value={search} aria-label="Search tasks" placeholder="Search tasks…"/>{#if search}<button class="icon-button" aria-label="Clear search" onclick={() => search = ''}><X size={13}/></button>{/if}</div>{/if}<a class="icon-button notifications-button" href="/notifications" aria-label="Notifications" onclick={(e) => go(e,'/notifications')}><Bell size={19}/>{#if notices.unread}<span></span>{/if}</a><a class="avatar small purple" href="/settings" aria-label="User settings" onclick={(e) => go(e,'/settings')}>{initials(session.user.name)}</a></div></header>
      <main class="workspace-main">
        {#if storage?.content_blocked}<div class="notice danger capacity-banner"><HardDrive size={17}/><span>The database has reached its content threshold. Existing content remains available.</span>{#if session.user.role === 'editor'}<a href="/admin" onclick={(e) => go(e,'/admin')}>Manage storage</a>{/if}</div>{/if}
        <div class="page-heading"><div><span class="eyebrow">{projectId ? 'PROJECT' : screen === '/my-tasks' ? 'A LITTLE FOCUS GOES A LONG WAY' : 'YOUR WORK, TOGETHER'}</span><h1>{#if selectedProject}<span class="project-title-mark" style:--project-color={selectedProject.color}><Folder size={22}/></span>{/if}{title}{#if selectedProject?.archived_at}<span class="badge">Archived</span>{/if}</h1><p>{subtitle}</p></div><div class="heading-actions">{#if projectId && selectedProject}<button class="button secondary" onclick={() => projectOverview = !projectOverview}>Overview</button>{#if !selectedProject.archived_at && session.user.role === 'editor'}<button class="icon-button bordered" aria-label="Edit project" title="Edit project" onclick={() => projectEditor = selectedProject!}><MoreHorizontal size={19}/></button>{/if}{/if}{#if screen === '/projects' && session.user.role === 'editor'}<button class="button primary" disabled={storage?.content_blocked} onclick={() => projectEditor = 'new'}><Plus size={17}/>New project</button>{:else if isTaskScreen && screen !== '/archive' && !selectedProject?.archived_at && session.user.role === 'editor'}<button class="button primary" disabled={storage?.content_blocked} onclick={openNew}><Plus size={17}/>New task</button>{/if}</div></div>
        {#if projectOverview && selectedProject}<section class="project-overview"><Markdown value={selectedProject.description || '_No project description yet._'}/>{#if session.user.role === 'editor'}<button class="button subtle" onclick={() => projectAction(selectedProject!)}>{#if selectedProject.archived_at}<RefreshCw size={15}/>Restore project{:else}<Archive size={15}/>Archive project{/if}</button>{/if}</section>{/if}
        {#if isTaskScreen}
          <div class="view-bar"><div class="tabs"><button class:active={mode === 'list'} onclick={() => mode = 'list'}><List size={16}/>List</button>{#if screen !== '/archive'}<button class:active={mode === 'board'} onclick={() => mode = 'board'}><Columns3 size={16}/>Board</button>{/if}</div><span class="view-count">{tasks.length}{hasMore ? '+' : ''} {tasks.length === 1 ? 'task' : 'tasks'}</span><div class="spacer"></div><span class="shared-label"><span class="online-dot"></span>Shared with everyone</span></div>
          <div class="filter-bar"><SlidersHorizontal size={15}/><select aria-label="Filter status" bind:value={filterStatus}><option value="active">{screen === '/archive' ? 'All statuses' : 'Active tasks'}</option><option value="all">All statuses</option>{#each statuses as item}<option value={item.value}>{item.label}</option>{/each}</select>{#if screen !== '/my-tasks'}<select aria-label="Filter assignee" bind:value={filterAssignee}><option value="">All assignees</option>{#each users as person}<option value={String(person.id)}>{person.name}{person.active ? '' : ' (deactivated)'}</option>{/each}</select>{/if}{#if !projectId}<select aria-label="Filter project" bind:value={filterProject}><option value="">All projects</option>{#each projects as project}<option value={String(project.id)}>{project.name}</option>{/each}</select>{/if}<div class="spacer"></div><button class="text-button" onclick={() => void refreshTasks()}><RefreshCw size={13}/>Refresh</button></div>
          {#if listError}<div class="notice danger" role="alert">{listError}<button class="text-button" onclick={() => void refreshTasks()}>Try again</button></div>
          {:else if loading}<div class="loading-state"><span class="spinner"></span>Gathering your tasks…</div>
          {:else if !tasks.length}<div class="empty-state"><div class="empty-icon">{#if screen === '/archive'}<Archive size={28}/>{:else}<CheckCheck size={30}/>{/if}</div><h2>{search || filterAssignee || filterProject ? 'Nothing quite matches.' : screen === '/archive' ? 'A clean slate.' : screen === '/my-tasks' ? 'A little room to breathe.' : 'Ready for your next idea.'}</h2><p>{search || filterAssignee || filterProject ? 'Try a different search or loosen up your filters.' : screen === '/archive' ? 'Deleted tasks will wait here until an editor restores or permanently deletes them.' : screen === '/my-tasks' ? 'No tasks in this view. Explore what your team is working on.' : 'Tasks will appear here when an editor adds them.'}</p>{#if screen !== '/archive' && !selectedProject?.archived_at && session.user.role === 'editor'}<button class="button primary" onclick={openNew}><Plus size={16}/>{activeProjects.length ? 'Create a task' : 'Create your first project'}</button>{/if}</div>
          {:else if mode === 'board' && screen !== '/archive'}<div class="board">{#each statuses as column}<section class="board-column" aria-label={`${column.label} tasks`} ondragover={(e) => { if (session?.user.role === 'editor') e.preventDefault(); }} ondrop={(e) => { e.preventDefault(); if (session?.user.role !== 'editor') return; const task = tasks.find(t => t.id === dragging); if (task) void changeStatus(task,column.value); dragging = null; }}><div class="board-column-heading"><span class={`status-dot ${column.value}`}></span><h2>{column.label}</h2><span class="count">{tasks.filter(t => t.status === column.value).length}</span></div><div class="board-cards">{#each tasks.filter(t => t.status === column.value) as task}<button class="board-card" class:selected={task.id === taskId} aria-current={task.id === taskId ? 'true' : undefined} draggable={session.user.role === 'editor'} ondragstart={() => dragging = task.id} ondragend={() => dragging = null} onclick={() => navigate(`/tasks/TB-${task.id}`)}><div class="board-card-top"><span class="mono">TB-{task.id}</span><MoreHorizontal size={15}/></div><strong>{task.title}</strong><span class="board-project"><span class="project-dot" style:--project-color={task.project_color}></span>{task.project_name}</span><div class="board-card-footer"><span class:overdue={task.overdue}><CalendarDays size={13}/>{dateLabel(task.due_date)}</span>{#if task.assignee_name}<span class="avatar small" title={task.assignee_name}>{initials(task.assignee_name)}</span>{:else}<span class="unassigned-avatar">—</span>{/if}</div></button>{:else}<div class="board-drop">{session.user.role === 'editor' ? 'Drop a task here' : 'No tasks'}</div>{/each}</div></section>{/each}</div>
          {:else}<div class="task-table"><div class="task-table-heading"><span>Task</span><span>Project</span><span>Status</span><span>Assignee</span><span>{screen === '/archive' ? 'Archived' : 'Due date'}</span></div>{#each tasks as task}<div class="task-row" class:selected={task.id === taskId}><div class="task-title-cell"><button class={`task-check ${task.status}`} aria-label={task.status === 'done' ? `Reopen TB-${task.id}` : `Complete TB-${task.id}`} title={session.user.role === 'editor' ? task.status === 'done' ? 'Reopen task' : 'Mark done' : 'Viewers cannot change tasks'} disabled={!!task.archived_at || session.user.role !== 'editor'} onclick={() => changeStatus(task,task.status === 'done' ? 'todo' : 'done')}>{#if task.status === 'done'}<Check size={12}/>{:else if task.status === 'canceled'}<X size={12}/>{/if}</button><a href={`/tasks/TB-${task.id}`} aria-current={task.id === taskId ? 'true' : undefined} onclick={(e) => go(e,`/tasks/TB-${task.id}`)}><span class="task-reference">TB-{task.id}</span><span class:completed={task.status === 'done'}>{task.title}</span></a></div><a class="project-cell" href={`/projects/${task.project_id}`} onclick={(e) => go(e,`/projects/${task.project_id}`)}><span class="project-dot" style:--project-color={task.project_color}></span><span class="truncate">{task.project_name}</span></a><span><span class={`status-badge ${task.status}`}><span class={`status-dot ${task.status}`}></span>{statusLabel(task.status)}</span></span><div class="assignee-cell">{#if task.assignee_name}<span class="avatar small">{initials(task.assignee_name)}</span><span class="truncate">{task.assignee_name}</span>{:else}<span class="muted">Unassigned</span>{/if}</div><span class="due-cell" class:overdue={task.overdue}><CalendarDays size={13}/>{screen === '/archive' && task.archived_at ? new Date(task.archived_at).toLocaleDateString() : dateLabel(task.due_date)}</span></div>{/each}</div>{/if}
          {#if hasMore && !loading}<div class="load-more"><span>Showing {tasks.length} tasks</span><button class="button secondary" onclick={moreTasks}>Load more</button></div>{/if}
        {:else if screen === '/projects'}
          <div class="project-list-toolbar"><span>{projects.filter(p => !!p.archived_at === showArchivedProjects).length} {showArchivedProjects ? 'archived' : 'active'} projects</span><label class="checkbox-label"><input type="checkbox" bind:checked={showArchivedProjects}/>Show archived projects</label></div><div class="project-grid">{#each projects.filter(p => !!p.archived_at === showArchivedProjects) as project}<a class="project-card" href={`/projects/${project.id}`} onclick={(e) => go(e,`/projects/${project.id}`)}><div class="project-card-top"><span class="project-title-mark" style:--project-color={project.color}><Folder size={22}/></span><ArrowUpRight size={18}/></div><h2>{project.name}</h2><p>{project.description.replace(/[#*_`\[\]]/g,'').slice(0,140) || 'A shared space for your team’s next steps.'}</p><div class="project-progress"><span style:width={`${project.task_count ? project.done_count / project.task_count * 100 : 0}%`} style:background={project.color}></span></div><div class="project-card-footer"><span>{project.done_count} of {project.task_count} tasks done</span><span>{project.task_count ? Math.round(project.done_count / project.task_count * 100) : 0}%</span></div></a>{:else}<div class="empty-state"><div class="empty-icon"><Folder size={28}/></div><h2>{showArchivedProjects ? 'No archived projects.' : 'Every project starts somewhere.'}</h2><p>{showArchivedProjects ? 'Archived projects will appear here.' : session.user.role === 'editor' ? 'Create a shared home for your first set of tasks.' : 'Projects will appear here when an editor creates them.'}</p>{#if !showArchivedProjects && session.user.role === 'editor'}<button class="button primary" onclick={() => projectEditor = 'new'}><Plus size={16}/>Create a project</button>{/if}</div>{/each}</div>
        {:else if screen === '/notifications'}
          <div class="inbox-toolbar"><span>{notices.unread} unread updates</span><button class="button secondary" onclick={() => markRead()} disabled={!notices.unread}><CheckCheck size={16}/>Mark all read</button></div><div class="notice-list">{#each notices.items as notice}<a class:unread={!notice.read_at} href={`/tasks/TB-${notice.task_id}`} onclick={(e) => { void markRead(notice.id); go(e,`/tasks/TB-${notice.task_id}`); }}><span class="notice-kind">{#if notice.kind === 'due'}<CalendarDays size={20}/>{:else}<Bell size={19}/>{/if}</span><div><p>{notice.message}</p><small>{timestamp(notice.created_at,session.user.timezone)}</small></div>{#if !notice.read_at}<span class="unread-dot"></span>{/if}<ChevronRight size={17}/></a>{:else}<div class="empty-state"><div class="empty-icon"><Inbox size={30}/></div><h2>You're all caught up.</h2><p>Watch a task to follow its progress. Your updates will find you here.</p></div>{/each}</div>{#if notices.has_more}<div class="load-more"><button class="button secondary" onclick={async () => { try { const next = await api<NotificationPage>(`/notifications?page=${notices.page+1}`); notices = { ...next, items: [...notices.items,...next.items] }; } catch (e) { notify(errorMessage(e)); } }}>Load earlier updates</button></div>{/if}
        {:else if screen === '/settings'}<Settings {session} {storage} onsaved={() => { void api<Session>('/auth/me').then(s => { session = s; setCsrf(s.csrf); }).catch(e => notify(errorMessage(e))); }} onpasswordchanged={() => { session = null; setCsrf(''); changeRoute('/login'); notify('Password updated. Sign in with your new password.'); }}/>
        {:else if screen === '/admin' && session.user.role === 'editor'}<Admin {users} {storage} onchanged={() => void refreshMeta().catch(e => notify(errorMessage(e)))}/>
        {:else}<div class="empty-state"><h2>This page isn't available.</h2><a class="button primary" href="/my-tasks" onclick={(e) => go(e,'/my-tasks')}>Back to your tasks</a></div>{/if}
        <footer class="workspace-footer"><span>taskboard<span class="brand-dot">.</span></span><span>A little clarity. A lot of possibility.</span></footer>
      </main>
    </div>
  </div>
  {#if newTask || taskId}{#key taskId ?? 'new'}<TaskModal bind:this={taskEditor} id={taskId} {projects} {users} user={session.user} defaultProject={projectId || undefined} onclose={() => { newTask = false; if (taskId) changeRoute(backTo); }} onsaved={savedTask}/>{/key}{/if}
  {#if projectEditor && session.user.role === 'editor'}<ProjectModal project={projectEditor === 'new' ? undefined : projectEditor} onclose={() => projectEditor = null} onsaved={(project) => { projectEditor = null; void changed(); navigate(`/projects/${project.id}`); notify('Project saved.'); }}/>{/if}
{/if}
{#if toast}<div class="toast" role="status"><Check size={16}/><span>{toast.message}</span>{#if toast.action}<button onclick={toast.action}>{toast.label}</button>{/if}<button class="icon-button" aria-label="Dismiss notification" onclick={() => toast = null}><X size={15}/></button></div>{/if}
